# Generated by Django 5.1.7 on 2025-03-09 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_subject_teacher_attendance_subject_teacher_exam_and_more'),
        ('attendance', '0003_user_email_verified_user_otp'),
    ]

    operations = [
    ]
