# Generated by Django 5.1.6 on 2025-03-15 05:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_alter_student_batch"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="batch",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="attendance.batch",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="teacher",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="attendance.teacher",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="is_present",
            field=models.CharField(
                choices=[("Present", "Present"), ("Absent", "Absent")],
                default="Absent",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="attendance.student",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="attendance.subject",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="attendancereport",
            name="attendance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="attendance.attendance",
            ),
        ),
        migrations.AlterField(
            model_name="attendancereport",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="attendancereport",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_reports",
                to="attendance.student",
            ),
        ),
        migrations.AlterField(
            model_name="attendancereport",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("student", "subject", "date")},
        ),
    ]
