# Generated by Django 5.1.6 on 2025-03-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_user_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="student",
            name="roll_no",
            field=models.CharField(max_length=10),
        ),
    ]
