# Generated by Django 5.1.6 on 2025-03-15 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_attendance_batch_attendance_teacher_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="attendance.batch",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="attendance.teacher",
            ),
        ),
    ]
