# Generated by Django 5.1.6 on 2025-03-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0004_user_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="gender",
            field=models.CharField(
                blank=True, default="male", max_length=10, null=True
            ),
        ),
    ]
