# Generated by Django 5.1.6 on 2025-03-11 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0006_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="course_id",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="attendance.course",
            ),
        ),
    ]
