# Generated by Django 5.1.6 on 2025-03-12 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0007_student_course_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                default="STUDENT",
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="student_model",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
